### ISSUE TITLE
How to figure out what color is responsible for

### ISSUE THREAD

**Issue by webcaptcha** [tinted-theming/base16-termite#11]
When I downloaded colors config and apply it to termit, mostly I have noticed background is changed.
How I can understand fro example
```
# Yellow
color3  = #a06e3b
color11 = #a06e3b
```
where yellow color is using?

**Comment by khamer** [comment]
Its setting the 16 colors for terminals, you can see them running something like
```
$ for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$i;$a""m$i;$a""m\e[0m "; done; echo; done
```
or
```
$ npx colortest
```

base16 only provides 16 colors, half of which are typically a gray scale, so it only have one yellow per scheme - the bold variants that terminals have are just set to reuse the same yellow as non-bold.
