### ISSUE TITLE
There's no wiki to preview the themes

### ISSUE THREAD

**Issue by GijsTimmers** [tinted-theming/base16-termite#3]
I would be willing to upload a few images of what the themes actually look like, so other users don't have to walk over all the themes.

**Comment by Kallinteris-Andreas** [comment]
that would be awesome

**Comment by tsaber** [comment]
[start](http://imagizer.imageshack.com/img924/5223/QQy5LW.png)

**Comment by khamer** [comment]
I've added a whole directory of images here

- https://github.com/khamer/base16-termite/tree/master/screenshots

I'm not sure what the best way to get them all into the wiki would be.

**Comment by JamyGolden** [comment]
You can preview the themes here: https://base16-project.github.io/base16-gallery/. It might be worth adding a line about previewing the themes with that gallery to all of the template repos readmes :thinking:
