### ISSUE TITLE
Error: invalid color string: rgba(29, 32, 33)

### ISSUE THREAD

**Issue by theova** [tinted-theming/base16-termite#9]
Hi there!

Thanks for the cool colorschemes!

When I'm starting `termite` from another instance, I get the following error message:
```
$ termite
invalid color string: rgba(29, 32, 33)
```

 If I change `rgba(..)` to `rgb(..)`, the error message is gone, but I'm not sure, if this is the solution.
I can't recognize any optical problem.

**Comment by phcerdan** [comment]
Yeah, it is missing the 4th number (alpha/transparency).
We can fix it either with `rgb(29, 32, 33)` or `rgba(29, 32, 33, 0.8)`

**Comment by khamer** [comment]
This is resolved now (believe it or not) - swapped out using rgb() for the plain hex.
